# Numpy
# Pandas
# Scikit-learn

In [1]:
# numpy

import numpy as np

x = [1, 2, 3, 4, 5] # normal python list
y = np.array(x) # numpy array
y

array([1, 2, 3, 4, 5])

In [3]:
type(x)

list

In [5]:
x = np.array([[1, 2, 3],
	[4,5,6]])
x.ndim

2

In [6]:
x.shape

(2, 3)

In [7]:
x.size

6

In [8]:
x = np.arange(1, 10, 2)

In [9]:
x

array([1, 3, 5, 7, 9])

In [10]:
x = np.array([[1,2,3], [4,5,6]])

In [11]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
print(x.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [15]:
z = np.zeros((2,3))

In [16]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
z = np.ones((3,2))

In [18]:
z

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
import pandas as pd

In [20]:
df = pd.DataFrame({"A": [1,2,3], "B": [4,5,6]})

In [21]:
df

A  B
0  1  4
1  2  5
2  3  6

In [22]:
s = pd.Series([1,2,3,4,5], index = ['A', 'B', 'C', 'D', 'E'])

In [23]:
s

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [25]:
s["A"]

np.int64(1)

In [26]:
s = pd.Series([1,2,3,4,5])

In [28]:
s.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64